import { Sidebar } from "@/ui/organisms";
import type { Metadata } from "next";
import "./dashboardStyles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Sidebar />
        <main className="content-dashboard">

            {children}
        </main>
      </body>
    </html>
  );
}
