import { Sidebar } from "@/ui/organisms";
import type { Metadata } from "next";
import "./dashboardStyles.scss";
import GuardAuth from "../Guard/GuardAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GuardAuth>
      <Sidebar />
      <main className="content-dashboard">
          {children}
      </main>
    </GuardAuth>
  );
}
