import type { Metadata } from "next";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <main className="main-public">
            {children}
        </main>
      </body>
    </html>
  );
}
